import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=async name=>JSON.parse(await readFile(path.join(root,'content',name),'utf8'));
const data=await read('workshops.json'),research=await read('research.json'),genealogy=await read('genealogy.json'),memories=await read('memories.json'),descendants=await read('descendants.json');
const E=(s='')=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rel=(from,to)=>path.posix.relative(path.posix.dirname(from),to)||'index.html';
const L=(from,to,label,attrs='')=>`<a href="${E(rel(from,to))}"${attrs}>${label}</a>`;
const X=(url,label,attrs='')=>`<a href="${E(url)}"${attrs}>${E(label)}</a>`;
const route=(id,s='')=>`${id}/${s?s+'/':''}index.html`;
const nav=[['index.html','Home','home'],['ecc/index.html','ECC','ecc'],['cdc/index.html','CDC','cdc'],['festschrift/index.html','Festschrift','festschrift'],['liber-amicorum/index.html','Liber amicorum','liber-amicorum']];
const honoree={name:'Rodolphe Sepulchre',slug:'rodolphe-sepulchre',affiliation:'KU Leuven',profileUrl:'https://sites.google.com/site/rsepulchre/home',portrait:'assets/portraits/rodolphe-sepulchre.jpg',roleLabel:'Honoree',focus:'Control, interaction and rhythms'};
const favicon='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" fill="white"/><text x="8" y="43" font-family="Arial,sans-serif" font-size="32" font-weight="700" fill="#172b42">60</text></svg>');
function header(from,active){return `<header class="site-header wrap">${L(from,'index.html','Sepulchre <span>60</span>',' class="brand" aria-label="Sepulchre 60 home"')}<nav aria-label="Main navigation">${nav.map(([url,label,id])=>L(from,url,label,` class="nav-button"${active===id?' aria-current="page"':''}`)).join('')}</nav></header>`;}
function footer(from){return `<footer class="site-footer wrap"><p>Sepulchre 60 · 2027</p><p>${X(honoree.profileUrl,'Rodolphe’s webpage')} · ${L(from,'sources/index.html','Sources & credits')}</p></footer>`;}
function doc(from,title,body,active='home'){return `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Sepulchre 60: ICE at ECC and FIRE at CDC 2027, an academic tree, a Festschrift and a Liber amicorum."><title>${E(title==='Sepulchre 60'?title:title+' — Sepulchre 60')}</title><link rel="icon" type="image/svg+xml" href="${favicon}"><link rel="stylesheet" href="${rel(from,'assets/style.css')}"></head><body><a class="skip-link" href="#main">Skip to content</a>${header(from,active)}<main id="main">${body}</main>${footer(from)}</body></html>\n`;}
function banner(from){return `<div class="staff wrap" aria-hidden="true"><img src="${rel(from,'assets/hh-staff.svg')}" width="1000" height="86" alt=""></div>`;}
function title(from,h1,subtitle,text=''){return `<section class="page-title wrap"><h1>${E(h1)}</h1>${subtitle?`<p class="subtitle">${E(subtitle)}</p>`:''}${text?`<p class="introduction">${E(text)}</p>`:''}</section>${banner(from)}`;}
function subnav(w,from,current){return `<nav class="workshop-nav wrap" aria-label="${E(w.conference)} navigation">${[['','Home'],['academic-tree','Academic tree'],['programme','Programme']].map(([s,label])=>L(from,route(w.id,s),label,` class="nav-button"${s===current?' aria-current="page"':''}`)).join('')}</nav>`;}
function person(p,from){return `<article class="person" id="${E(p.slug)}"><a href="${E(p.profileUrl)}" aria-label="${E(p.name)} — professional webpage"><img src="${rel(from,p.portrait)}" alt="${E(p.name)}" width="200" height="200" loading="lazy" decoding="async"></a><h3>${X(p.profileUrl,p.name)}</h3><p>${E(p.affiliation)}</p>${p.roleLabel?`<p class="person-period">${E(p.roleLabel)}</p>`:p.joinYear?`<p class="person-period">${E(p.joinRole)} · from ${p.joinYear}</p>`:''}</article>`;}
function home(){const from='index.html';return doc(from,'Sepulchre 60',title(from,'Sepulchre 60','')+`<figure class="wrap honoree-quote"><img src="${honoree.portrait}" alt="Rodolphe Sepulchre" width="150" height="150"><figcaption>${X(research.musicUrl,'“Music is rhythmic. So is life.”',' title="Rodolphe Sepulchre, Clocks and Rhythms (2022)"')}</figcaption></figure><section class="wrap event-index workshop-layout" aria-labelledby="workshops-heading"><div class="workshop-list"><h2 id="workshops-heading">Workshops in 2027</h2><dl>${data.workshops.map(w=>`<div><dt>${L(from,route(w.id),E(w.name+' @ '+w.conference))}<span class="workshop-theme">${E(w.title)}</span></dt><dd><strong>${E(w.date)}</strong><br>${E(w.city)} · ${E(w.audience)}</dd></div>`).join('')}</dl><p class="status">Both workshops are proposed; acceptance and speaker participation remain to be confirmed.</p></div><div class="ice-fire-circle"><img src="assets/ice-fire-enso.png" width="1254" height="1254" alt="A Zen-like circle formed by two brushstrokes, one ice blue and one fire orange"><a class="circle-half ice-half" href="ecc/index.html" aria-label="ICE at ECC 2027" title="ICE at ECC 2027"></a><a class="circle-half fire-half" href="cdc/index.html" aria-label="FIRE at CDC 2027" title="FIRE at CDC 2027"></a></div></section><section class="wrap collection-index"><h2>Memories</h2><p>The ${L(from,'festschrift/index.html','Festschrift')} gathers academic contributions inspired by Rodolphe’s work. The ${L(from,'liber-amicorum/index.html','Liber amicorum')} brings together friends’ recollections, photographs and shared moments.</p></section>`);}
function logistics(w){return `<section id="logistics" class="wrap logistics"><h2>Practical information</h2><dl class="logistics-list"><div><dt>Date</dt><dd>${E(w.dateDetail)}</dd></div><div><dt>Venue</dt><dd>${E(w.venue)}. ${E(w.venueDetail)}</dd></div><div><dt>Registration</dt><dd>${E(w.registration)}</dd></div><div><dt>Travel</dt><dd>${E(w.travel)}</dd></div><div><dt>Lunch & dinner</dt><dd>Lunch is included in the draft timetable. Catering, dinner venue and any charges are to be confirmed.</dd></div><div><dt>Organisers & contact</dt><dd>The organising committee and workshop contact will be announced once agreed.</dd></div><div><dt>Conference</dt><dd>${X(w.officialUrl,w.officialLabel)}${w.workshopSource?`<br>${X(w.workshopSource,w.workshopSourceLabel)}`:''}</dd></div></dl></section>`;}
function workshopHome(w){const from=route(w.id),ps=[...w.speakers,honoree];return doc(from,`${w.conference} — ${w.title}`,title(from,w.displayName,w.title,w.description)+subnav(w,from,'')+`<div class="workshop-facts wrap"><span>${E(w.date)}</span><span>${E(w.city)}, ${E(w.country)}</span><span>One-day pre-conference workshop</span></div><section class="speaker-band"><div class="wrap"><h2>Speakers</h2><p class="status">Provisional list · invitations and attendance are not yet confirmed.</p><div class="speaker-grid ${w.id==='ecc'?'ecc-grid':'cdc-grid'}">${ps.map(p=>person(p,from)).join('')}</div></div></section>${logistics(w)}`,w.id);}
function schedule(w,from){return `<div class="schedule" role="list">${w.programme.map(s=>{const p=s.person===honoree.slug?honoree:w.speakers.find(p=>p.slug===s.person);return `<div class="schedule-row ${s.kind==='break'?'break':''}" role="listitem"><div class="schedule-time">${E(s.time)}</div><div class="schedule-content">${p?`<h3>${L(from,route(w.id)+'#'+p.slug,E(p.name))}</h3><p>${E(s.title||'Talk title to be announced')}</p><p class="schedule-meta">${p.joinYear?`${E(p.joinRole)} · joined ${p.joinYear} · `:''}${w.talkMinutes}-minute talk + ${w.questionMinutes}-minute discussion</p>`:`<h3>${E(s.title)}</h3>${s.detail?`<p>${E(s.detail)}</p>`:''}`}</div></div>`;}).join('')}</div>`;}
function programme(w){const from=route(w.id,'programme');return doc(from,`${w.conference} programme`,title(from,w.displayName,`${w.title} · Programme`)+subnav(w,from,'programme')+`<section class="wrap programme"><h2>${E(w.date)} · ${E(w.city)}</h2><p>${E(w.programmeDescription)}</p><p class="status">Tentative programme · local time. Talk titles and participation are to be confirmed.</p>${schedule(w,from)}${w.id==='ecc'?`<details class="editorial-details"><summary>How the order was established</summary><p>${E(data.chronologyNote)}</p><ul>${(data.chronologyCaveats||[]).map(c=>`<li>${E(c.text)} ${c.sources.map((s,i)=>X(s,`Source ${i+1}`)).join(' · ')}</li>`).join('')}</ul><p>${X('https://sites.google.com/site/rsepulchre/phds-postdocs','Rodolphe’s PhD and postdoc roster')}</p></details>`:''}</section>`,w.id);}
function lineageEntry(n){return `<li class="lineage-node ${E(n.kind||'doctoral')}"><div><strong>${n.url?X(n.url,n.name):E(n.name)}</strong>${n.meta?`<span>${E(n.meta)}</span>`:''}${n.note?`<small>${E(n.note)}</small>`:''}${n.otherParent?`<aside class="other-parent"><span>Another teacher of ${E(n.shortName||n.name)}</span><strong>${X(n.otherParent.url,n.otherParent.name)}</strong><small>${E(n.otherParent.meta)}</small></aside>`:''}</div>${n.edgeLabel?`<p class="edge-label">${E(n.edgeLabel)}${n.edgeUrl?' · '+X(n.edgeUrl,'source'):''}</p>`:''}</li>`;}
function genealogyPanel(g){return `<section class="lineage-panel"><h2>${E(g.title)}</h2><p class="lineage-subtitle">${E(g.subtitle)}</p>${g.context?`<p class="lineage-context">${E(g.context)}</p>`:''}${g.groups.map(group=>group.collapsed?`<details class="lineage-group"><summary>${E(group.title)}</summary><ol class="lineage">${group.entries.map(lineageEntry).join('')}</ol></details>`:`${group.title?`<h3 class="lineage-group-title">${E(group.title)}</h3>`:''}<ol class="lineage">${group.entries.map(lineageEntry).join('')}</ol>`).join('')}${g.note?`<p class="lineage-note">${E(g.note)}</p>`:''}<p class="lineage-end">${E(g.finalRelation)}${g.finalSource?' · '+X(g.finalSource,'source'):''}</p></section>`;}
function descendantTree(){const people=(category)=>descendants.people.filter(p=>p.category===category).sort((a,b)=>a.startYear-b.startYear||a.name.localeCompare(b.name));const list=category=>`<ul class="descendant-list">${people(category).map(p=>`<li id="${E(category+'-'+p.slug)}">${X(p.profileUrl||p.sourceUrl,p.name,p.profileUrl?'':' title="Listed on Rodolphe’s PhD and postdoc roster"')}<span>${E(p.listedPeriod)}</span></li>`).join('')}</ul>`;return `<section class="research-descendants" aria-label="Rodolphe’s PhD students and postdoctoral researchers"><div class="descendant-branches">${[['phd','PhD students'],['postdoc','Postdoctoral researchers']].map(([branch,label])=>`<section class="descendant-branch"><h2>${label}</h2><div class="current-descendants"><h3>Current <span>${descendants.counts['current-'+branch]}</span></h3>${list('current-'+branch)}</div><details class="former-descendants" open><summary>Former <span>${descendants.counts['former-'+branch]}</span></summary>${list('former-'+branch)}</details></section>`).join('')}</div><p class="descendant-note">${descendants.counts.uniquePeople} people, connected through ${descendants.counts.entries} PhD and postdoctoral roles. Six people appear in both branches. Periods and current/former status follow ${X(descendants.sourceUrl,'Rodolphe’s official roster')} as checked in September 2026; the periods are not degree-award dates. Names link to individual profiles where available, otherwise to the roster.</p></section>`;}
function tree(w){const from=route(w.id,'academic-tree');return doc(from,`${w.conference} academic tree`,title(from,'Academic tree',`${w.conference} · Two routes into Rodolphe’s work`)+subnav(w,from,'academic-tree')+`<section class="wrap genealogy"><p class="tree-introduction">${E(genealogy.introduction)}</p><div class="tree-legend"><span class="solid-key">Doctoral / research training</span><span class="dashed-key">Earlier teacher–student or historical link</span></div><div class="lineages">${genealogy.panels.map(genealogyPanel).join('')}</div><div class="shared-descendant"><strong>${X(honoree.profileUrl,'Rodolphe Sepulchre')}</strong><span>Systems & control</span></div>${w.id==='ecc'?descendantTree():''}<details class="editorial-details"><summary>Sources, historical conventions and unresolved links</summary>${genealogy.notes.map(n=>`<p>${E(n)}</p>`).join('')}<ul>${genealogy.sources.map(s=>`<li>${X(s.url,s.label)}</li>`).join('')}</ul></details></section>`,w.id);}
function festschrift(){const from='festschrift/index.html';return doc(from,'Festschrift',title(from,'A Festschrift for Rodolphe','Scholarly contributions on the occasion of his 60th birthday')+`<section class="wrap prose"><h2>About the volume</h2><p>This collection is intended to bring together mathematical ideas, research perspectives and open questions connected with Rodolphe’s work. Contributions may develop a scientific result, revisit a shared problem, or explain how an idea has travelled between fields.</p><p>Nonlinear control, geometry, optimisation, collective dynamics and biological rhythms provide possible starting points. The purpose is to make the science—and the questions still ahead—available as a lasting academic record.</p><h2>Contributions</h2><p>Manuscripts will be listed here with their authors, abstracts and downloadable papers as they are received. No submitted contributions are available yet.</p><details class="editorial-details"><summary>Preparing a contribution</summary><p>A contribution should include a title, author names and affiliations, an abstract, the main text and references. A short note or a longer article is welcome in this draft format; length, editorial process and deadlines will be agreed by the organisers.</p><p>${L(from,'assets/templates/academic-contribution.md','Download a simple manuscript outline',' download')}</p></details><h2>Background reading</h2><p>A selection from Rodolphe’s books, papers and editorials provides context for the volume.</p><ol class="bibliography">${research.readings.map(r=>`<li>${X(r.url,r.title)} <span>(${E(r.year)})</span><p>${E(r.authors)}</p></li>`).join('')}</ol><p>${X('https://sites.google.com/site/rsepulchre/publications','Full publication list')}</p></section>`,'festschrift');}
function memoriesPage(){const from='liber-amicorum/index.html';return doc(from,'Liber amicorum',title(from,'Liber amicorum','Friends, conversations and shared moments')+`<section class="wrap prose"><p>A place for personal recollections: a conversation that stayed with us, a problem worked through together, a journey, a meal, or a moment of music.</p><h2>From the public archive</h2><p class="status">The photographs below are documented public archive images. Friends’ personal recollections will be added when contributed.</p></section><section class="wrap memory-gallery">${memories.photos.map(p=>`<figure><a href="${E(p.sourcePage)}"><img src="${rel(from,p.asset)}" alt="${E(p.alt||p.caption)}" width="${p.width}" height="${p.height}" loading="lazy"></a><figcaption><h2>${E(p.title)}</h2><p>${E(p.caption)}</p><p class="photo-credit">${E(p.credit)} · ${X(p.sourcePage,'Source')}${p.licenseUrl?' · '+X(p.licenseUrl,p.license):''}</p></figcaption></figure>`).join('')}</section><section class="wrap prose"><h2>Friends’ recollections</h2><p>Contributed memories will appear here with the writer’s name, photographs and captions. This section is awaiting personal contributions.</p><details class="editorial-details"><summary>Preparing a memory</summary><p>A few paragraphs and one or more photographs are enough. Include your name, the people shown, the place and approximate date, and a photographer credit where known. Please choose material you are happy to have included in the collection.</p><p>${L(from,'assets/templates/memory-contribution.md','Download a simple contribution outline',' download')}</p></details></section>`,'liber-amicorum');}
function sources(){const from='sources/index.html';return doc(from,'Sources & credits',title(from,'Sources & credits','Profiles, portraits, genealogy and the banner')+`<section class="wrap prose"><p>Speaker confirmations have not been supplied. The two workshop directories are therefore presented as provisional lists. Public profiles are linked from every name and portrait.</p><p>The banner traces a simulated Hodgkin–Huxley action potential on five staff lines. ${L(from,'assets/hh-model.json','Model and source notes')} · ${L(from,'assets/hh-trace.csv','Simulation data')}</p><p>The ICE/FIRE brush circle is an original generated illustration. The quotation, “Music is rhythmic. So is life.”, is from Rodolphe’s ${X(research.musicUrl,'Clocks and Rhythms (2022)')}.</p><p>Rodolphe’s portrait: ${X(research.portraitSource,'KU Leuven')}.</p><p>Layout reference: ${X('https://people.kth.se/~mikaelj/rantzer_fest/index.html','Anders Rantzer’s 60th-birthday workshop')}.</p><div class="credit-list">${data.workshops.flatMap(w=>w.speakers).map(p=>`<section id="${E(p.slug)}"><h2>${E(p.name)}</h2><p>${X(p.profileUrl,'Professional profile')} · ${X(p.relationshipSource,'Research connection')}</p><p>${E(p.portraitCredit)} · ${X(p.portraitPageUrl||p.profileUrl,'Portrait source')}</p></section>`).join('')}</div></section>`);}
function redirect(from,to){const target=rel(from,to);return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0;url=${E(target)}"><title>Sepulchre 60</title><link rel="stylesheet" href="${rel(from,'assets/style.css')}"></head><body><main id="main" class="wrap prose"><h1>Sepulchre 60</h1><p><a href="${E(target)}">Continue to the updated page</a></p></main></body></html>\n`;}
const outputs=new Map([['index.html',home()],['festschrift/index.html',festschrift()],['liber-amicorum/index.html',memoriesPage()],['memories/index.html',redirect('memories/index.html','liber-amicorum/index.html')],['sources/index.html',sources()]]);
for(const w of data.workshops){outputs.set(route(w.id),workshopHome(w));outputs.set(route(w.id,'academic-tree'),tree(w));outputs.set(route(w.id,'programme'),programme(w));outputs.set(route(w.id,'speakers'),redirect(route(w.id,'speakers'),route(w.id)+'#speakers'));outputs.set(route(w.id,'logistics'),redirect(route(w.id,'logistics'),route(w.id)+'#logistics'));}
for(const [old,id] of [['ice','ecc'],['fire','cdc']])for(const s of ['','speakers','programme','logistics'])outputs.set(route(old,s),redirect(route(old,s),route(id,s==='programme'?'programme':'')+(s==='speakers'?'#speakers':s==='logistics'?'#logistics':'')));
outputs.set('programme/index.html',redirect('programme/index.html','ecc/programme/index.html'));outputs.set('research/index.html',redirect('research/index.html','festschrift/index.html'));outputs.set('practical/index.html',redirect('practical/index.html','ecc/index.html#logistics'));
for(const [name,html] of outputs){const target=path.join(root,'dist',name);await mkdir(path.dirname(target),{recursive:true});await writeFile(target,html.replace('<section class="speaker-band">','<section class="speaker-band" id="speakers">'));}
await writeFile(path.join(root,'dist/.nojekyll'),'');
console.log(`Rendered ${outputs.size} static pages, including legacy URL forwards.`);
